services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  server:
    build: ./server
    container_name: server_container
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - ./server:/app
      - /server/node_modules
    environment:
      - MONGO_URL=mongodb://mongo:27017/book-collection

  client:
    build: ./client
    container_name: client_container
    ports:
      - "3000:3000"
    depends_on:
      - server
    stdin_open: true
    tty: true
    volumes:
      - ./client:/app
      - /client/node_modules
    environment:
      - REACT_APP_BACKEND_BASE_URL=http://localhost:8080/api

volumes:
  mongo_data: